# warm up lambda by cron job
name: health-check
"on":
  schedule:
    - cron: "*/30 * * * *"
jobs:
  health-check:
    runs-on: ubuntu-20.04
    container:
      image: badouralix/curl-jq
    steps:
      - run: curl -sf https://youtube-dl-web-hiro18181.vercel.app/healthz | jq --exit-status
